on:
  push:
    branches: [main]

name: Deploy prod infra

jobs:
  docker_image_deploy:
    name: Deploy prod Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: wget Dockerfile
        uses: wei/wget@v1
        with:
          args: -O Dockerfile https://raw.githubusercontent.com/UWAMakers/access-api/master/Dockerfile


      - name: Build, tag, and push image
        id: build-image
        run: |
          docker build -t uwashl/access:latest .
          docker push uwashl/access:latest